# Generated by Django 4.1.7 on 2023-04-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbiote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor_assign',
            old_name='supervisor_name',
            new_name='supervisor_username',
        ),
    ]
