# Generated by Django 4.1.7 on 2023-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiote', '0002_rename_supervisor_name_supervisor_assign_supervisor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor_assign',
            name='project_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
