# Generated by Django 4.1.7 on 2023-04-15 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiote', '0002_alter_attendence_area_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence_area',
            old_name='Employee_id',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='attendence_area',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='attendence_area',
            name='Time',
        ),
        migrations.AlterField(
            model_name='absenteism_count',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 15)),
        ),
        migrations.AddField(
            model_name='attendence_area',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 15)),
        ),
        migrations.AddField(
            model_name='attendence_area',
            name='time',
            field=models.TimeField(default=datetime.time(12, 41, 9, 437087)),
        ),
    ]
