# Generated by Django 4.1.7 on 2023-04-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbiote', '0003_supervisor_assign_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor_assign',
            name='assign_work_at',
        ),
    ]
