# Generated by Django 4.1.7 on 2023-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiote', '0005_employee_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
